### ISSUE TITLE
Unable to profile executable on 64bit Ruby on Windows

### ISSUE THREAD

**Issue by ashmaroli** [rbspy/rbspy#175]
### Ruby Version
```sh
ruby -v
# => ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]
```
### rbspy Version
```sh
rbspy --version
# => rbspy 0.3.2
```
(installed artifact from: https://ci.appveyor.com/project/jvns/rbspy/build/job/mlyah8e6on7jmp7u/artifacts
into `/Ruby24-x64/bin`)

### Jekyll Version
```sh
bundle exec jekyll --version
# => jekyll 3.8.3
```
### Attempts to profile building site with Jekyll
```sh
rbspy record bundle exec jekyll build
# => Error. Causes:
#    - The system cannot find the file specified. (os error 2)

rbspy record jekyll build
# => Error. Causes:
#    - The system cannot find the file specified. (os error 2)
```

**Comment by benfred** [comment]
Instead of launching like ```rbspy record jekyll build``` can you try going ```rbspy record ruby c:\Ruby24-x64\bin\jekyll build```?  Making this change lets me profile jekyll on my windows system (and I get the same error message as you otherwise).

On windows, jekyll installs a 'jekyll.bat' file to your ruby bin directory - and it's this batch file that gets launched when you go ```jekyll build```.  We're using rusts' ```Command::new``` to create the process, and on Windows this uses the CreateProcess api - which doesn't handle batch files (and even if it did, we don't follow subprocesses yet on windows - so the launched program would be a cmd.exe process running the batch file rather than the ruby process it spawns). In the short term this means you need to either pass in the PID of a ruby program, or pass a command line that directly runs ruby
