### ISSUE TITLE
Line numbers aren't reported in traces on Ruby 2.6.x

### ISSUE THREAD

**Issue by jvns** [rbspy/rbspy#213]

**Comment by neosilky** [comment]
To anyone wanting to look into this:

I added support for 2.6.x in #210. The internal structs changed a little so it required a new `get_lineno` function.

I couldn't figure out how to extract the `positions` table. [Line 517](https://github.com/rbspy/rbspy/pull/210/files#diff-8f2c9a69304ac81cec4ba41fb9e92340R517) errors before it can do the logic.

It might be worth looking at the line numbering logic anyway. I'm not entirely convinced it's working correctly in 2.5.x either.

**Comment by acj** [comment]
I think the main issue is that `insns_info.positions` is often 0 (at least for our CI test programs), which means we would take the [`else` branch in .gdbinit](https://github.com/ruby/ruby/blob/f9b62b5cc04fa87f0970c9ca3d1cbbc9be8bf8fe/.gdbinit#L1030-L1050) and will need to implement the "succinct bitvector" lookup. It's math-intensive but compact. Might not be too bad if someone runs gdb and adds a few `printf`s to ruby's .gdbinit so that the individual values can be printed and compared as the rust code is being written.

**Comment by dalehamel** [comment]
This may also be an issue in 3.1.0, i'm doing some digging as to why but I'm seeing many line numbers report as `0` but other information is correct.

**Comment by acj** [comment]
Ruby 2.6 reached EOL status about 18 months ago, so there's probably limited value in fixing this. If anyone needs line numbers to work, the code [here](https://github.com/acj/rbspy/commit/75e0e6ee625dff9ff5fc2a49da6a065ed892efa6) might be a helpful starting point, but be warned that it wasn't working consistently enough to ship.
