### ISSUE TITLE
Doesn't build on FreeBSD

### ISSUE THREAD

**Issue by ntinti** [rbspy/rbspy#230]
```
   Compiling read-process-memory v0.1.2
   Compiling term_size v0.3.1
error[E0432]: unresolved import `platform`
  --> /usr/local/registry/src/github.com-1ecc6299db9ec823/read-process-memory-0.1.2/src/lib.rs:38:9
   |
38 | pub use platform::Pid;
   |         ^^^^^^^^ maybe a missing crate `platform`?

error[E0432]: unresolved import `platform`
  --> /usr/local/registry/src/github.com-1ecc6299db9ec823/read-process-memory-0.1.2/src/lib.rs:40:9
   |
40 | pub use platform::ProcessHandle;
   |         ^^^^^^^^ maybe a missing crate `platform`?

error[E0433]: failed to resolve: use of undeclared type or module `platform`
  --> /usr/local/registry/src/github.com-1ecc6299db9ec823/read-process-memory-0.1.2/src/lib.rs:60:53
   |
60 |     fn try_into_process_handle(&self) -> io::Result<platform::ProcessHandle> {
   |                                                     ^^^^^^^^ use of undeclared type or module `platform`

   Compiling clap v2.33.0
error: aborting due to 3 previous errors

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: Could not compile `read-process-memory`.
warning: build failed, waiting for other jobs to finish...
```

I wish it works like py-spy does
https://github.com/benfred/py-spy/issues/112

**Comment by jvns** [comment]
If py-spy builds on freebsd rbspy certainly can be made to build on freebsd
as well. I'd be happy to merge a PR that adds FreeBSD support.

>

**Comment by benfred** [comment]
py-spy does support freebsd now - thanks to the work by @akhramov . 

I ended up forking read-process-memory and py-spy is accessing through the forked version on crates.io https://crates.io/crates/benfred-read-process-memory . This fork goes back to the first version of py-spy, I wanted to this change https://github.com/luser/read-process-memory/pull/6/commits/bdc674428e6c4cadf29518e4d3ce1a869efbfbd0 since it roughly doubled the overall profiling speed on OSX - and didn't get it merged in to the original repo. This fork now has that osx change as well as the freebsd code.

Switching to my fork of read-process-memory and bumping the proc-maps version to pull in the freebsd changes will probably be sufficient to get rbspy at least building on freebsd.

There is also some code in py-spy that might also be helpful https://github.com/benfred/py-spy/tree/master/remoteprocess - this has some cross platform utilities for doing things like locking the process. Locking the process is necessary for FreeBSD (uses ptrace calls to copy memory).  While the read-process-memory changes will work without it, if we haven't already done a ptrace attach every read memory call will lock individually which might hurt performance.

**Comment by akhramov** [comment]
I have created #238, which migrates rbspy to py-spy's remoteprocess crate and automatically getting FreeBSD support for (almost) free.

Early adopters, testers and reviewers are very welcome.

**Comment by akhramov** [comment]
@ntinti my PR's been landed to master. May I ask you to try it out to see if it suits your needs well?

**Comment by acj** [comment]
We've had a functioning FreeBSD build for a while, so I'm going to close this. I added it back to our CI matrix so that the build will stay healthy. I haven't had a chance to test rbspy on FreeBSD recently, though. Please open a new issue if there are any problems with it.
