### ISSUE TITLE
Recording stops prematurely with no errors

### ISSUE THREAD

**Issue by wagenet** [rbspy/rbspy#243]
I'v been consistently finding that my recordings stop prematurely (even with a duration specified) without any sort of notification as to why. I checked the docs and couldn't find any information about what might cause this.

**Comment by wagenet** [comment]
This seems to be specific to macOS.

**Comment by wagenet** [comment]
I realized I could turn on logger with RUST_LOG and discovered that it is stopping because of `MemoryCopyError::ProcessEnded`.

**Comment by acj** [comment]
Possibly related to #263 even though the error output is different. I've run into this as well on busy systems, and it's happened a couple of times while I've been working on ruby 3 support and profiling simple sinatra servers. The latter makes me think that the early exits happen because of an illegal memory access or something similar. I'm not sure why we'd get a `process exited` error in that case, though. Maybe a library bug where macOS's error code is misinterpreted?

I'll try to chase this down once the ruby 3 work lands.
