### ISSUE TITLE
Move release from Travis to GitHub Actions

### ISSUE THREAD

**Issue by jvns** [rbspy/rbspy#293]
travis-ci.org seems to be slowly removing support for OSS projects and so I think it would be good at some point to move off Travis entirely and onto github actions. (CI is already on GitHub Actions)

This would let us upload release binaries for more architectures (since we're already building those artifacts in the GitHub Actions CI). The Travis script only uploads Mac and linux x86 artifacts right now.

**Comment by dalehamel** [comment]
I have a lot of experience moving things from travis to github actions, like github.com/iovisor/bpftrace, I could take a stab at this if no one else gets to it!

**Comment by acj** [comment]
Ohai @dalehamel :) It's been a while!

I've been nibbling around the edges but haven't started working on the release part. If you have time, I'd be grateful for the help. The commit that you linked to is what I have in mind for the set of release file attachments.

Roughly: when a new tag is pushed, attach the same files that we currently build in CI, and maybe generate a draft set of release notes that we can edit (list of merge commit messages since the last tag would be fine). Maybe mark it as a pre-release so that we have time to review and edit the notes before it's official. I'm flexible on the details, but something like that.
