### ISSUE TITLE
Support using rbspy as a library

### ISSUE THREAD

**Issue by acj** [rbspy/rbspy#320]
There's been some discussion of building rbspy as both a binary and a library, e.g. in #180. This would enable other Rust (and C, maybe others) programs to use rbspy as a native library instead of shelling out to run the binary. The [Pyroscope fork](https://github.com/pyroscope-io/rbspy) of rbspy has already taken a step in this direction.

We also have prior art in py-spy: https://github.com/benfred/py-spy/issues/110.

This shouldn't require too much work. I think we'll want to audit the public surface area of the existing modules to make sure that they're an API we're comfortable maintaining. It's probably okay to make breaking changes until we reach 1.0, but I'd like us to make a reasonable effort to start out with a clean API.

**Comment by petethepig** [comment]
Hi @acj

We at Pyroscope would love to contribute to this effort. Currently we integrate with rbspy, py-spy and phpspy by building them as static libraries and then linking them to pyroscope. We forked these libraries and added APIs that look like this:

```c
// initializes a spy for a given pid
int rbspy_init(pid_t pid, void* err_ptr, int err_len);

// releases resources associated with a given pid
int rbspy_cleanup(pid_t pid, void* err_ptr, int err_len);

// takes a snapshot for a given pid
int rbspy_snapshot(pid_t pid, void* ptr, int len, void* err_ptr, int err_len);
```

We tried to make the API as small and simple as possible so that it's easy to integrate into existing C / C++ / Rust / Go code. That's why we avoided passing any sort of structs or anything like that. 

But it's also pretty limited and so we'd love to work with you to come up with a better, extendable, more standardized api that others could use.

**Comment by acj** [comment]
@petethepig Hi! That's great to hear. I think it makes sense to support a minimal API with reasonable defaults for the reasons you mentioned. It would be nice to also support passing a struct of options (with primitive, portable types) so that clients can use rbspy's recording feature and easily control sampling behavior.

I have a local branch that starts to implement this and that should be in a sharable state soon (a week or two). It doesn't have C bindings yet, but based on your fork it should be straightforward to add them. Let's work on that together once the PR is open. I don't expect that we'll get all the details right on the first try, which seems fine -- we can iterate on the library API as rbspy approaches 1.0 and try to minimize breaking changes.
