### ISSUE TITLE
Error: version `GLIBC_2.33' not found (required by rbspy)

### ISSUE THREAD

**Issue by mscrivo** [rbspy/rbspy#375]
Been using rbspy in our docker images for quite some time without any issues, but after upgrading to Ruby 3.2, we're now seeing this error when trying to run rbspy:

```
rbspy: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by rbspy)
rbspy: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by rbspy)
rbspy: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by rbspy)
```

Our image is pretty standard, we're building from ruby:3.2.0-slim-bullseye and we're installing rbspy 0.15 like this:

```
    curl -sSL https://github.com/rbspy/rbspy/releases/download/v0.15.0/rbspy-${ARCH}-unknown-linux-gnu.tar.gz | \
    tar -xzf - && mv rbspy-${ARCH}-unknown-linux-gnu rbspy && chmod a+x rbspy && \
    rm -rf rbspy-${ARCH}-unknown-linux-gnu.tar.gz && \
```

looking at the libc files in `/lib/x86_64-linux-gnu`, it seems that only 2.31 is installed. Was this a recent requirement change in rbspy?

**Comment by acj** [comment]
Can you try using the x86_64-musl build instead of gnu? It's a static binary and should work with most base images. (Looks good on `ruby:3.2.0-slim-bullseye` here.)

There was no intentional requirement change, but this can happen depending on which glibc version ships with the base image you're using. We upgraded the CI to Ubuntu 22.04 between the 0.13.0 and 0.13.1 releases. My guess is that that's when the target glibc version changed. Thanks for the report.

**Comment by mscrivo** [comment]
That worked! Thanks @acj
