### ISSUE TITLE
May I know the max sampling rate rbspy can support?

### ISSUE THREAD

**Issue by yfractal** [rbspy/rbspy#389]
When I set the rate to more than 20_000 in my local machine(Mac m3 pro), it reports `traces were sampled late`.

May I know how to increase this rate? And what factors affect this rate?

I'm asking this, because I'm curious, could I use Rbspy to profile an extremely low latency programs, for example, 0.1ms

**Comment by acj** [comment]
rbspy doesn't have a maximum sampling rate because it's hard to predict. The main factors should be, in no specific order:
- CPU speed
- Other running programs that are actively using CPU
- Ruby version
- Complexity of the Ruby program being sampled (e.g. call stack depth)
- Number of child processes being sampled, if you're using `--subprocesses`
- Kernel configuration (mostly a factor on Linux)

I suggest experimenting with `--subprocesses` and `--nonblocking` to see if any combination gives you a higher rate.

I don't think we've heard from anyone working with very latency-sensitive programs, but it might be possible. Please let us know how it goes for you.

**Comment by yfractal** [comment]
Thanks a lot.
